c_compiler_version: # [linux]
  - 12              # [linux and (cuda_compiler_version or "").startswith("12")]
  - 11              # [linux and (cuda_compiler_version or "").startswith("11")]

c_stdlib_version:   # [linux]
  - 2.17            # [linux]
  - 2.17            # [linux]

cxx_compiler_version:   # [linux]
  - 12                  # [linux and (cuda_compiler_version or "").startswith("12")]
  - 11                  # [linux and (cuda_compiler_version or "").startswith("11")]

cuda_compiler:  # [linux]
  - nvcc        # [linux]
  - nvcc        # [linux]

cdt_name:   # [linux]
  - cos7    # [linux]
  - cos7    # [linux]

docker_image:                                   # [linux]
  - quay.io/condaforge/linux-anvil-cuda:11.8    # [linux]
  - quay.io/condaforge/linux-anvil-cuda:11.8    # [linux]

cuda_compiler_version:
  - 12.5
  - 11.8
