{% set name = "SegAlign" %}
{% set version = "0.1.2.6" %}
{% set segalign_tbb_version = "2020.2.*" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/richard-burhans/SegAlign/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cb80ce5bfa1e7b3d909364d384a60343d901984201016e666102615c67093c2e

build:
  number: 0
  skip: true  # [win or cuda_compiler_version is undefined or cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make
  host:
    - cuda-version {{ cuda_compiler_version }}
    - libboost-devel
    - tbb-devel {{ segalign_tbb_version }}
    - zlib
  run:
    - bash
    - coreutils
    - cuda-version {{ cuda_compiler_version }}
    - gawk
    - grep
    - sed
    - tbb-devel {{ segalign_tbb_version }}
    - time

test:
  commands:
    - segalign --help
    - segalign_repeat_masker --help

about:
  home: https://github.com/gsneha26/SegAlign
  summary: 'SegAlign: A Scalable GPU-Based Whole Genome Aligner'
  description: |
    SegAlign is a Scalable GPU System for Pairwise Whole Genome
    Alignments based on LASTZ's seed-filter-extend paradigm.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/gsneha26/SegAlign/blob/main/README.md
  dev_url: https://github.com/gsneha26/SegAlign

extra:
  recipe-maintainers:
    - richard-burhans
