{% set name = "SegAlign" %}
{% set version = "0.1.2.7" %}
{% set segalign_tbb_version = "2020.2.*" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/galaxyproject/SegAlign/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3b6da023a3014b1560c2b3fa5275961ebc5c82eea66a90a55e426fa15c619e6c

build:
  number: 3
  skip: true  # [win or osx or cuda_compiler_version is undefined or cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make
  host:
    - cuda-version {{ cuda_compiler_version }}
    - libboost-devel
    - tbb-devel {{ segalign_tbb_version }}
    - zlib
  run:
    - {{ pin_compatible("cuda-version", min_pin="x.x", max_pin="x") }}
    - bash
    - coreutils
    - gawk
    - grep
    - sed
    - tbb-devel {{ segalign_tbb_version }}
    - time

test:
  commands:
    - segalign --help
    - segalign_repeat_masker --help

about:
  home: https://github.com/galaxyproject/SegAlign
  summary: 'SegAlign: A Scalable GPU-Based Whole Genome Aligner'
  description: |
    SegAlign is a Scalable GPU System for Pairwise Whole Genome
    Alignments based on LASTZ's seed-filter-extend paradigm.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/galaxyproject/SegAlign/blob/main/README.md
  dev_url: https://github.com/galaxyproject/SegAlign

extra:
  recipe-maintainers:
    - richard-burhans
    - galaxyproject/segalign
