{% set name = "SegAlign" %}
{% set version = "0.1.2" %}
{% set tbb_version = '2020.2.*' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gsneha26/SegAlign/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4f1892d0a08acf98b40608a2938cab984c225362df7a4c28c8347f2f38071abb
  patches:
    - patches/d1a73a0c9169d5517c9316d9bdc68fd52f63e885.patch
    - patches/CMakeLists.txt.patch
    - patches/common__seed_pos_table.cu.patch
    - patches/repeat_masker_src__seed_filter.cu.patch
    - patches/src__seed_filter.cu.patch

build:
  number: 1
  skip: true  # [cuda_compiler_version is undefined or cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake
    - make
  host:
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - libboost-devel
    - tbb-devel {{ tbb_version }}
    - zlib
  run:
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - parallel
    - tbb-devel {{ tbb_version }}

test:
  commands:
    - segalign --help
    - segalign_repeat_masker --help

about:
  home: https://github.com/gsneha26/SegAlign
  summary: 'SegAlign: A Scalable GPU-Based Whole Genome Aligner'
  description: |
    SegAlign is a Scalable GPU System for Pairwise Whole Genome
    Alignments based on LASTZ's seed-filter-extend paradigm.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/gsneha26/SegAlign/blob/main/README.md
  dev_url: https://github.com/gsneha26/SegAlign

extra:
  recipe-maintainers:
    - richard-burhans
    # need to ask first
    #- gsneha26     Sneha D. Goenka
    #- yatisht      Yatish Turakhia
    #- glennhickey  Glenn Hickey
