{% set name = "SegAlign" %}
{% set version = "0.1.2.1" %}
{% set tbb_version = '2020.2.*' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/richard-burhans/SegAlign/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2c04c662015eb7846a0f1e3a817169ed31d218338296840e3989cbb19f602e7e

build:
  number: 0
  skip: True  # [win or cuda_compiler_version is undefined or cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake
    - make
  host:
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - libboost-devel
    - tbb-devel {{ tbb_version }}
    - zlib
  run:
    - coreutils
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - grep
    - sed
    - tbb-devel {{ tbb_version }}

test:
  commands:
    - segalign --help
    - segalign_repeat_masker --help

about:
  home: https://github.com/gsneha26/SegAlign
  summary: 'SegAlign: A Scalable GPU-Based Whole Genome Aligner'
  description: |
    SegAlign is a Scalable GPU System for Pairwise Whole Genome
    Alignments based on LASTZ's seed-filter-extend paradigm.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/gsneha26/SegAlign/blob/main/README.md
  dev_url: https://github.com/gsneha26/SegAlign

extra:
  recipe-maintainers:
    - richard-burhans
    # need to ask first
    #- gsneha26     Sneha D. Goenka
    #- yatisht      Yatish Turakhia
    #- glennhickey  Glenn Hickey
